[project]
name = "desktop-maskot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "atproto>=0.0.61",
    "customtkinter>=5.2.2",
    "pillow>=11.2.1",
    "requests>=2.32.3",
]
